SecretaryDEK/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView
from django.contrib.auth.decorators import login_required
from secretary import views, urls as APIs
from schedule import urls as SchAPIs


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url('', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^$', login_required(views.show_page), name='home'),
    url(r'^users/logout/$', auth_views.logout, kwargs={'next_page': 'base'}, name='auth_logout'),
    url(r'^register/complete/$', RedirectView.as_view(pattern_name='base'), name='registration_complete'),
    url(r'^users/', include('registration.backends.simple.urls', namespace='users')),
    url('^diploma/add$', login_required(views.DiplomaCreate.as_view()), name='diploma_add'),
    url(r'^api/', include(APIs)),
    url(r'^api/', include(SchAPIs)),

    # url(r'^api/lol_data', tests.guide_add_data),
]

schedule/urls.py
__author__ = 'masterbob'
"""
URL's of API's. Kinda close and sturdy.
"""
from django.conf.urls import include, url
from schedule import api
from rest_framework.authtoken import views as rest_views

urlpatterns = [
    url(r'^handper/(?P<id>[0-9]+)', api.HandingPeriodUpd.as_view()),
    url(r'^handper', api.HandingPeriodView.as_view()),
    url(r'^handday/(?P<id>[0-9]+)', api.HandingDayUpd.as_view()),
    url(r'^handday', api.HandingDayView.as_view()),
    ]

secretary/urls.py
__author__ = 'masterbob'
"""
URL's of API's. Kinda close and sturdy.
"""
from django.conf.urls import include, url
from secretary import api
from rest_framework.authtoken import views as rest_views

urlpatterns = [
    url(r'^example', api.ExampleView.as_view()),
    url(r'^login', rest_views.obtain_auth_token),
    url(r'^diploma/(?P<id>[0-9]+)', api.DiplomasUpd.as_view()),
    url(r'^diploma', api.DiplomasView.as_view()),
    url(r'^logout', api.TokenRenderView.as_view()),
    url(r'^reviewer/(?P<id>[0-9]+)', api.ReviewersUpd.as_view()),
    url(r'^reviewer', api.ReviewersView.as_view()),
    url(r'^student/(?P<user>[0-9]+)', api.StudentUpd.as_view()),
    url(r'^student', api.StudentView.as_view()),
    url(r'^chief/(?P<id>[0-9]+)', api.ChiefUpd.as_view()),
    url(r'^chief', api.ChiefView.as_view()),
    url(r'^group/(?P<id>[0-9]+)', api.GroupUpd.as_view()),
    url(r'^group', api.GroupView.as_view()),
    url(r'^studrestrict/(?P<id>[0-9]+)', api.StudentsRestrictionsUpd.as_view()),
    url(r'^studrestrict', api.StudentsRestrictionsView.as_view()),
    url(r'^commission/(?P<id>[0-9]+)', api.CommissionUpd.as_view()),
    url(r'^commission', api.CommissiontView.as_view()),
    url(r'^general/(?P<users>[0-9]+)', api.GeneralUpd.as_view()),
    url(r'^general', api.GeneralView.as_view()),
    url(r'^user/(?P<id>[0-9]+)', api.UsersUpd.as_view()),
    url(r'^user', api.UsersView.as_view()),
    ]

secretary/models.py
from django.db import models
from django.contrib.auth.models import User
from schedule.models import HandingDay, HandingPeriod
# Create your models here.

# For UserType we using builtin model User, that contain authorization and authentication
class Group(models.Model):
    """
    Dummy group purposed mostly for dropdowns
    """
    id = models.IntegerField(verbose_name='Id', primary_key=True, unique=True, db_index=True,
                             auto_created=True, blank=True)
    name = models.CharField(verbose_name="Група",max_length=40)
    barchelor = "бакалавр"
    specialist = "спеціаліст"
    phd = "магістр"
    maigster = phd
    choices = (
        (barchelor, "Бакалавр"),
        (specialist, "Спеціаліст"),
        (phd, "Магістр")
    )
    spec = models.CharField(verbose_name="напрямок (Бакалавр, Спеціаліст чи Магістр)",max_length=40, choices=choices,
                            default="Бакалавр")
    ipdo = models.BooleanField(verbose_name="ІПДО?")

    def __str__(self):
        return self.name

class Reviewer(models.Model):
    """
    Reviewer ORM. Holds typical name, surname, mname and a ID. For now.
    """
    #id = models.IntegerField(verbose_name='Id', primary_key=True, unique=True, db_index=True, auto_created=True,
    #                         blank=True)
    #user = models.OneToOneField(User, primary_key=True)
    children = models.IntegerField(null=True, verbose_name='Діти, шт.', blank=True)
    education = models.CharField(null=True, max_length=250, verbose_name="Освіта",blank=True)
    special_education = models.CharField(null=True, max_length=40, verbose_name="Спеціальна освіта",blank=True)
    academic_status = models.CharField(null=True, max_length=10, verbose_name="Вчене звання",blank=True)
    degree = models.CharField(null=True, max_length=10, verbose_name="Науковий ступінь",blank=True)
    position = models.CharField(null=True, max_length=250, verbose_name="Посада",blank=True)
    workplace = models.CharField(null=True, max_length=250, verbose_name="Місце роботи",blank=True)
    bdate = models.DateField(null=True, verbose_name="Дата народження", blank=True)
    mname = models.CharField(null=False, max_length=100, verbose_name="По-батькові")
    home = models.CharField(null=True, max_length=250, verbose_name="Місце проживання", blank=True)
    passseries = models.CharField(null=True, max_length=5, verbose_name="Серія паспорта", blank=True)
    passnum = models.IntegerField(null=True, verbose_name="Номер паспорта", blank=True)
    passplace = models.CharField(max_length=50, null=True, verbose_name="Ким виданий", blank=True)
    passdate = models.DateField(null=True, verbose_name="Коли виданий", blank=True)
    idnum = models.CharField(max_length=13, null=True, verbose_name="Ідентифікаційний код", blank=True)
    def __str__(self):
        return self.user.last_name + ' ' + self.user.first_name


class Chief(models.Model):
    """
    Diploma Chief ORM. Holds typical name, surname, mname and a ID. For now.
    """
    #id = models.IntegerField(verbose_name='Id', primary_key=True, unique=True, db_index=True,
    #                         auto_created=True, blank=True)
    user = models.OneToOneField(User, primary_key=True)
    education = models.CharField(null=True, max_length=250, verbose_name="Освіта",blank=True)
    special_education = models.CharField(null=True, max_length=40, verbose_name="Спеціальна освіта",blank=True)
    academic_status = models.CharField(null=True, max_length=10, verbose_name="Вчене звання",blank=True)
    degree = models.CharField(null=True, max_length=10, verbose_name="Науковий ступінь",blank=True)
    position = models.CharField(null=True, max_length=250, verbose_name="Посада",blank=True)
    bdate = models.DateField(null=True, verbose_name="Дата народження", blank=True)
    home = models.CharField(null=True, max_length=250, verbose_name="Місце проживання", blank=True)
    passseries = models.CharField(null=True, max_length=5, verbose_name="Серія паспорта", blank=True)
    passnum = models.IntegerField(null=True, verbose_name="Номер паспорта", blank=True)
    passplace = models.CharField(max_length=50, null=True, verbose_name="Ким виданий", blank=True)
    passdate = models.DateField(null=True, verbose_name="Коли виданий", blank=True)
    idnum = models.CharField(max_length=13, null=True, verbose_name="Ідентифікаційний код", blank=True)
    def __str__(self):
        return self.user.last_name + ' ' + self.user.first_name


class General(models.Model):
    """
    User extention ORM. Foreign key - UserType.
    ID == PK
    Standard fields are in the User Model
    Date Fields - bdate (Birth) and entry2uni
    Boolean Field - registered
    """
    # id = models.IntegerField(verbose_name='Id', primary_key=True, unique=True, db_index=True, auto_created=True)
    user = models.OneToOneField(User, primary_key=True)
    mname = models.CharField(null=False, max_length=100, verbose_name="По-батькові")
    registered = models.BooleanField(verbose_name="Валідний?")

    def __str__(self):
        return self.user.last_name + ' ' + self.user.first_name
    def full_name(self):
        return self.user.last_name + ' ' + self.user.first_name + ' ' + self.mname
    def full_name_abbreviated(self):
        return self.user.last_name + ' ' + self.user.first_name[0] + '.' + self.mname[0] + '.'


class Student(models.Model):
    """

    """
    user = models.OneToOneField(User, primary_key=True)
    entry2uni = models.DateField(verbose_name="Дата вступу в універ")
    group = models.ForeignKey(Group)
    def __str__(self):
        return self.user.last_name + ' ' + self.user.first_name


class Diploma(models.Model):
    """
    Diplomas ORM. Contains many fields. Such as:
    Theme, year, group, review date, guide mark,
    number of pages in diploma, number of slides in the presentation
    Diploma Mark, Graduation Date(datehanding)
    Boolean Fields are type (is it a red diploma or NO) and fellowship
    Foreign Keys are Reviewer and Guide
    """
    # id = models.IntegerField(verbose_name='Id',primary_key=True, unique=True, db_index=True, auto_created=True)
    student = models.OneToOneField(Student)
    theme = models.TextField(max_length=512, verbose_name="Тема")
    theme_eng = models.TextField(max_length=512, verbose_name="Тема англійською", blank=True)
    group = models.ForeignKey(Group)
    reviewer = models.ForeignKey(Reviewer, related_name="Рецензент", blank=True, null=True, verbose_name="Рецензент",
                                 db_constraint=False)
    datereview = models.DateField(verbose_name='Дата рецензації', blank=True)
    chief = models.ForeignKey(Chief, blank=True, null=True, related_name="Керівник", verbose_name="Керівник",
                              db_constraint=False)
    chiefmark = models.IntegerField(null=True, verbose_name='Оцінка керівника', blank=True)
    numberofpages = models.IntegerField(null=True, verbose_name='Клькість сторінок в записці', blank=True)
    numberofslides = models.IntegerField(null=True, verbose_name='Кількість слайдів у презентації', blank=True)
    handingdate = models.ForeignKey(HandingDay, to_field='date', verbose_name="Дата захисту", null=True,blank=True,)
    type = models.BooleanField( verbose_name='Захищений?', default=False)
    handed = models.BooleanField( verbose_name='Диплом-то червоний?', blank=True)
    approval = models.BooleanField( verbose_name='Диплом-то зарев’юваний?', default=False)
    fellowship = models.BooleanField( verbose_name='Рекомендований в аспірантуру?', blank=True)
    commissionmark = models.IntegerField(null=True, verbose_name='Оцінка', blank=True)
    special_circumstances = models.NullBooleanField(verbose_name="Спец обставини. Достроковий захист і проч.")
    number = models.IntegerField(verbose_name="Номер диплому в архіві",unique=True, blank=True, null=True)

    def __str__(self):
        return self.student.user.last_name + ' ' + self.student.user.first_name



class StudentsRestriction(models.Model):
    """
    Restriction for guides. If someone
    has 5 places and takes 20 students, it's something bad. Isn't it?
    """
    # id = models.IntegerField(verbose_name='Id',primary_key=True, unique=True, db_index=True, auto_created=True)
    chief = models.ForeignKey(Chief, verbose_name="Керівник дипломок", db_constraint=False)
    numberofstudents = models.IntegerField(verbose_name="Кількість студентів", blank=True)
    handingperiod = models.ForeignKey(HandingPeriod, verbose_name="Тиждень захистів", to_field='start', db_constraint=False)

    def __str__(self):
        return self.chief.user.last_name + ' ' + self.chief.user.first_name


class Commission(models.Model):
    handingday = models.OneToOneField(HandingDay,to_field='date', primary_key=True)
    chairman = models.ForeignKey(Chief, blank=True, null=True, related_name='chairman')
    commissioner1 = models.ForeignKey(Chief, blank=True, null=True, related_name='comm1')
    commissioner2 = models.ForeignKey(Chief, blank=True, null=True, related_name='comm2')
    commissioner3 = models.ForeignKey(Chief, blank=True, null=True, related_name='comm3')
    commissioner4 = models.ForeignKey(Chief, blank=True, null=True, related_name='comm4')
    commissioner5 = models.ForeignKey(Chief, blank=True, null=True, related_name='comm5')

secretary/views.py
from django.shortcuts import render, redirect
# Create your views here.
from .models import Diploma
from django.views.generic.edit import CreateView
from django.forms import ModelForm
from django.views.generic import DetailView
from django.core.urlresolvers import reverse_lazy
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, HTML, Field
from crispy_forms.bootstrap import FormActions

def show_base(request):
    return render(request, 'base.html')

def show_page(request):
    # Дізнатися хто ти?(Студік чи лектор)
    ansDiploma = Diploma.objects.filter(profile__user=request.user)
    # зареквестити відповідну модель
    return render(request, 'diploma_list.html', {"tasks": ansDiploma})


class BaseForm(ModelForm):
    class Meta:
        model = Diploma
        fields = "__all__"

    def __init__(self, *args, **kwargs):

        super(ModelForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper(self)

        # set form tag attributes
        # self.helper.form_action = reverse_lazy('task_add')
        self.helper.form_method = 'POST'
        self.helper.form_class = 'form-horizontal'

        # set form field properties
        self.helper.help_text_inline = True
        self.helper.html5_required = True
        self.helper.label_class = 'col-sm-2 control-label'
        self.helper.field_class = 'col-sm-10'
        self.helper.render_unmentioned_fields = True
        self.helper.layout[-1] = Layout(
            Field('description', css_class='input-xlarge'),
            FormActions(Submit('add_button', u'Зберегти', css_id='submit-id-send_button')))


class DiplomaCreateForm(BaseForm):

    def __init__(self, *args, **kwargs):
        BaseForm.__init__(self, *args, **kwargs)
        self.helper.form_action = reverse_lazy('diploma_add')


class DiplomaCreate(CreateView):
    model = Diploma
    form_class = DiplomaCreateForm
    template_name = "diploma_add.html"

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = self.request.user
        instance.save()
        return redirect(self.get_success_url())

    def get_success_url(self):
        return "%s?status_message=Завдання успішно додано" % reverse_lazy("home")


class DiplomaDetail(DetailView):
    model = Diploma
    context_object_name = "task"
    template_name = 'diploma_edit.html'

    def get_object(self):
        """
        Task view
        """
        object_task = super(TaskDetail, self).get_object()
        return object_task

secretary/templates/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8"/>
    <title>{% block meta_title %}{% endblock meta_title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.15.35/css/bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/4.9.1/bootstrap-social.min.css">
    {% block extra_css %} {% endblock extra_css %}
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>

<!-- Start Container -->
<div class="container">
    <!-- Start Header -->
    <div class="row" id="header">
        <div class="col-xs-6">
            <h1>МеГА СУПЕР пупер сервіс</h1>
        </div>
        {% if user.is_authenticated %}
            <div class="col-xs-4">
                <strong>{{ user.username }}</strong>
            </div>
            <!-- User's toolbar for authenticated users -->
            <div class="col-xs-2" id="user-toolbar">
                <span></span>
                <a href="{% url "users:auth_logout" %}">Logout</a>
            </div>
        {% else %}
            <!-- User's toolbar for anonymous users -->
            <div class="col-xs-6" id="user-toolbar">
                <a href="{% url "users:auth_login" %}">Login</a>
            </div>
        {% endif %}
    </div>
    <!-- End Header -->

    <!-- Start Content Columns -->
    <div class="row" id="content-columns">
        <div class="col-xs-12" id="content-column">
            <div style=" position: relative; top: 80px">
            {% block content %}{% endblock content %}
            </div>
        </div>
    </div>
    <!-- End Content Columns -->

    <!-- Start Footer -->
    <div class="row" id="footer">
        <div class="col-xs-12">
            &copy; 2016
        </div>
    </div>
    <!-- End Footer -->

</div>
<!-- End Container -->
<!-- Javascripts Inclusion -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.form/3.51/jquery.form.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment-with-locales.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.15.35/js/bootstrap-datetimepicker.min.js"></script>
{% block extra_javascript %} {% endblock extra_javascript %}
<script src="{% static "js/main.js" %}"></script>
</body>

</html>

secretary/templates/diploma_add.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}
{% block extra_css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css">
{% endblock extra_css %}
{% block meta_title %} TaskKiller {% endblock meta_title %}

{% block content %}

    <div class="page-header">
        <h2 class="form_header">Додати роботу</h2>
    </div>
    {% crispy form %}

{% endblock content %}

{% block extra_javascript %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/js/bootstrap-select.min.js"></script>
{% endblock extra_javascript %}

secretary/templates/diploma_edit.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}

{% block meta_title %} TaskKiller {% endblock meta_title %}

{% block content %}
    <div class="col-xs-12" id="content-header">
        <div class="page-header">
            <h2 class="form_header">Деталі завдання</h2>
        </div>
    </div>
    <div class="form">
        <p>Назва: {{ task.name }}</p>

        <p>Замовник: {{ task.customer }}</p>

        <p>Дата початку: {{ task.date_start | date }}</p>

        <p>Дата закінчення: {{ task.date_end }}</p>

        <p>Статус: {{ task.status }}</p>

        <div>{% if task.picture %}
            <img src="{{ task.picture.url }}" height="300"
                 width="300"/>
        {% else %}
            <img class="img-circle" src="{% static "img/default_user.png" %}"
                 height="30" width="30"/>
        {% endif %}</div>
        <h3>Опис: </h3>
        <div>{{ task.html_description | safe }}</div>
    </div>
{% endblock content %}

secretary/templates/diploma_list.html
{% extends "base.html" %}
{% load static from staticfiles %}


{% block meta_title %} Add Task {% endblock meta_title %}

{% block content %}
    <div style="text-align: center;">
        <h2 style="display: inline;">Список завдань:</h2>
        <a href="{% url "diploma_add" %}" class="btn btn-primary" style="float: right">Додати завдання</a>
    </div>
    <img class="loader" src="/static/img/loader.gif">
    <!-- Start Students Listing -->
    <table class="table table-striped">
        {% with order_by=request.GET.order_by reverse=request.GET.reverse %}
            <thead>
            <tr>
                <th><a href="#">#</a></th>
                <th>
                    <a href="">
                        Назва
                    </a>
                </th>
                <th>
                    <a href="">
                        Замовник
                    </a>
                </th>
                <th><a href="#">Статус</a></th>
                <th><a href="#">Дата початку</a></th>
                <th>
                    <a href="">
                        Дата закінчення
                    </a>
                </th>
                <th><a href="#">Часу залишилось</a></th>
                <th>Дії</th>
            </tr>
            </thead>
        {% endwith %}
        <tbody>
        {% for task in tasks %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><a href="" >{{ task.theme }}</a></td>
                <td><a href="#">{{ task.theme_eng}}</a></td>
                <td class="status">{{ task.group }}</td>
                <td></td>
                <td class="end"></td>
                <td class="elapsed"></td>
                <td>
                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle"
                                data-toggle="dropdown">Дія
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="" class="task-edit-form-link">Редагувати</a></li>
                            <li><a href="#">Змінити статус</a></li>
                            <li><a href="">Видалити</a></li>
                        </ul>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <!-- End Students Listing -->
{% endblock content %}